version: '3.7'

services:
  mariadb:
    build: ./requirements/mariadb/
    image: inception_mariadb
    container_name: mariadb
    volumes:
      - db_volume:/var/lib/mysql/
    env_file: 
      - .env
    networks:
      - internal_network
    restart: on-failure

  nginx:
    build: ./requirements/nginx/
    image: inception_nginx
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - wp_volume:/var/www/html
    env_file: 
      - .env
    ports: 
      - 443:443
    networks:
      - internal_network
    restart: on-failure

  wordpress:
    build: ./requirements/wordpress/
    image: inception_wordperss
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp_volume:/var/www/html
    env_file: 
      - .env
    ports:
      - 9000:9000
    networks:
      - internal_network
    restart: on-failure

  adminer:
    build: ./requirements/bonus/adminer
    image: inception_adminer
    container_name: adminer
    networks:
      - internal_network
    volumes:
      - db_volume:/var/lib/mysql/
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    restart: on-failure

volumes:
  wp_volume:
    name: wp_volume
    driver: local
    driver_opts:
      device: /Users/mel-behc/data/mariadb_volume
      type: none
      o: bind
  db_volume:
    name: db_volume
    driver: local
    driver_opts:
      device: /Users/mel-behc/data/wordpress_volume
      type: none
      o: bind
  
networks:
  internal_network:
    name: 'internal_network'
    driver: bridge


